### ISSUE TITLE
System-UI crash with version 1.1.1

### ISSUE THREAD

**Issue by madbehaviorus** [SecUSo/privacy-friendly-netmonitor#17]
When NetMonitor 1.1.1 (from f-droid) is running and i use the "pull down menu", then crash the system-ui.
And in few connections the certificate is displayed. The most connections displays: "PENDING" in version 1.1.1
I downgraded to version 1.0 and it works perfectly!

**Comment by Yonjuni** [comment]
@madbehaviorus Thanks for reporting. Could you tell us your Android version?

**Comment by madbehaviorus** [comment]
Of course, the Android Version is 6.0.1 (Stock-Rom) / Sony Z2 (last Patch from March 2016).

**Comment by schillef** [comment]
The PENDING information is the message that the SSL-Labs info is in fact pending (Since SSL-Labs has not cached every result and has to perform those). This can take up to two minutes and should be updated when refreshing.

**Comment by schillef** [comment]
The crash could be a problem with borken package information of other, installed apps NetMontor wants to access. Can't be shure without a eError-Stacktrace. We're currently working on that.

**Comment by Yonjuni** [comment]
@madbehaviorus Could you have a look at version 1.1.3?

**Comment by madbehaviorus** [comment]
With 1.1.3 and 1.1.4 it works perfectly! Thanks.
