### ISSUE TITLE
Some App Icons Too Big

### ISSUE THREAD

**Issue by anoadragon453** [SecUSo/privacy-friendly-netmonitor#22]
![screenshot_20170301-163247](https://cloud.githubusercontent.com/assets/1342360/23487776/23abed00-fe9d-11e6-9802-8b20e26fd07d.png)

As shown into he screenshot some app icons are presented too large. This is happening consistently with the F-droid app "Simple Bitcoin Widget". Probably something on their side but forcing the icon width and height may still be a good idea to avoid this from other apps.

**Comment by Yonjuni** [comment]
@anoadragon453 Thanks for reporting. Could you tell us device and Android version?

**Comment by Yonjuni** [comment]
Seems that this widget does not use different icon sizes see https://github.com/hwki/SimpleBitcoinWidget/tree/master/mobile/src/main/res/drawable so the problem comes from the widget.

**Comment by anoadragon453** [comment]
> @anoadragon453 Thanks for reporting. Could you tell us device and Android version?

Android 7.1.1, Nexus 6P if it's still relevant.

> Seems that this widget does not use different icon sizes

Thanks for investigating and posting an issue in their tracker. Is there a possible workaround so other apps who also implement their icon sizes incorrectly don't display the same issue?

**Comment by schillef** [comment]
Issue inluded in general bugfix *salute* pullrequest.

**Comment by Yonjuni** [comment]
Closed #22
