### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by darlkr** [SecUSo/privacy-friendly-netmonitor#28]
Why does your app DRM the screenshots? 

I get the "can't take screenshot due to limited space, or it isn't empowered by the app or the organisation"

I can take a screenshot of my home launcher. So it's not a space problem (5gb free).

**Comment by Yonjuni** [comment]
@darlkr The app uses the secure flag which blocks screenshots. The idea is to secure privacy sensitive data.

**Comment by darlkr** [comment]
What is the potential security benefit of doing so? If there is an intruder, who installed malware and requests screenshots or something, I don't see any issues with him seeing the connection your phone makes? If there is malware, I'm pretty sure he can do the very same thing this app does, without the user's knowledge.

It just sounds like a stupid idea, when I want to show my friend that MY system app doesn't make the same connections that his one does. Or email the developer of an offline app, asking what those connections are doing there...
