### ISSUE TITLE
Netmonitor is stopped

### ISSUE THREAD

**Issue by Maxnor** [SecUSo/privacy-friendly-netmonitor#29]
Netmonitor works for a few seconds and then I receive the message that Netmonitor was stopped. The message keeps popping up until I stop the service under settings/applications.
Galaxy S7 Edge with Android 6.0.1

**Comment by Maxnor** [comment]
I just noticed that Google Play offers version 1.1.4 compared to F-Droid where only 1.1.2 is online.
1.1.4 works for me without any problems.

**Comment by Yonjuni** [comment]
Version 1.1.4 is available for F-Droid too ;)

**Comment by Maxnor** [comment]
It wasn't available at that Time ;)
