### ISSUE TITLE
wrong layout in help activity

### ISSUE THREAD

**Issue by FroggieFrog** [SecUSo/privacy-friendly-netmonitor#36]
The layout in help activity is wrong.
https://github.com/SecUSo/privacy-friendly-netmonitor/blob/4c9bb5b062538282a47b95e904e8f227785bea43/app/src/main/java/org/secuso/privacyfriendlynetmonitor/Activities/HelpDataDump.java#L111
permissions.add should be sysuser.add

**Comment by Yonjuni** [comment]
Closed #36
