### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [SecUSo/privacy-friendly-netmonitor#41]
Hi @SecUSo

I found [this app](https://play.google.com/store/apps/details?id=co.DarkGreen.netmonitor) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app.

**Comment by Atavic** [comment]
:+1: that's a bad dev.

**Comment by Atavic** [comment]
:+1: that's a bad dev.

**Comment by Yonjuni** [comment]
As far as I understood the app has been removed.
