### ISSUE TITLE
crash on startup in old Android

### ISSUE THREAD

**Issue by pdgilbert** [SecUSo/privacy-friendly-netmonitor#68]
(possibly related to #57 ) Using Net Monitor  2.0 on Android 4.2.1 with Google Nexus phone. The first time startup crashes after the first couple of startup information screens. Further attempts to start the app crash immediately. If the app data is cleared then the first couple of screens will display again before the crash. The message is "Unfortunately, Net Monitor has stopped." In developer mode I get no additional messages.

This is a very old version of Android, many apps on F-droid indicate "Incompatible". Perhaps that is the fix, but hopefully not. On other phones I am using Net Monitor 2.0 and it works fine on Android 9 with Google Pixel 2 and on Android 6.0.1 with Axon A1R. I have not had the problem mentioned in #38 on Android 6.0. (Thanks for this great app.)

**Comment by sleep-yearning** [comment]
Can you check if this is still a problem with release 2.1? There were some fixes for older devices inside.

**Comment by pdgilbert** [comment]
Not a phone I use much anymore, but I pulled it out and charged it to test. Release 2.1 is not yet on F-Droid or Play Store. Is that a temporary situation, or are you thinking I would build it?

**Comment by sleep-yearning** [comment]
F-Droid builds always take some time, it's up now though.

**Comment by pdgilbert** [comment]
Yes,  2.1 on Android 4.2.1 with my Google Nexus phone seems to be working fine now. Thanks again for this great app.
